/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.frames;

import io.databases.databaseRegions;
import io.models.modelRegions;
import javax.swing.JOptionPane;

/**
 *
 * @author AlexanderMS
 */
public class frameUpdateRegions extends javax.swing.JFrame {
    databaseRegions db = new databaseRegions();
    /**
     * Creates new form frameAddData
     */
    public frameUpdateRegions() {
        initComponents();
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_region_id = new javax.swing.JLabel();
        jLabel_region_name = new javax.swing.JLabel();
        jTextField_region_id = new javax.swing.JTextField();
        jTextField_region_name = new javax.swing.JTextField();
        jButton_save = new javax.swing.JButton();
        jButton_abort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 61, 95));

        jLabel_region_id.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_region_id.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_region_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_region_id.setText("region_id");

        jLabel_region_name.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_region_name.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_region_name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_region_name.setText("region_name");

        jTextField_region_id.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_region_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_region_idActionPerformed(evt);
            }
        });

        jTextField_region_name.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jButton_save.setBackground(new java.awt.Color(18, 61, 95));
        jButton_save.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_save.setForeground(new java.awt.Color(255, 255, 255));
        jButton_save.setText("Simpan");
        jButton_save.setToolTipText("");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });

        jButton_abort.setBackground(new java.awt.Color(18, 61, 95));
        jButton_abort.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_abort.setForeground(new java.awt.Color(255, 255, 255));
        jButton_abort.setText("Batal");
        jButton_abort.setToolTipText("");
        jButton_abort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_abortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButton_save, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton_abort, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_region_id)
                    .addComponent(jLabel_region_name))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_region_name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_region_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_region_id)
                    .addComponent(jTextField_region_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_region_name)
                    .addComponent(jTextField_region_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_save)
                    .addComponent(jButton_abort))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        db.update_row_regions(new modelRegions(               
                Integer.valueOf(jTextField_region_id.getText()),
                jTextField_region_name.getText()                
        ));
        
            
        JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
        
        setVisible(false);

    }//GEN-LAST:event_jButton_saveActionPerformed

    private void jButton_abortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_abortActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton_abortActionPerformed

    private void jTextField_region_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_region_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_region_idActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_abort;
    public javax.swing.JButton jButton_save;
    private javax.swing.JLabel jLabel_region_id;
    private javax.swing.JLabel jLabel_region_name;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextField_region_id;
    public javax.swing.JTextField jTextField_region_name;
    // End of variables declaration//GEN-END:variables
}
