/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.frames;

import io.databases.databaseDependents;
import io.models.modelDependents;
import javax.swing.JOptionPane;

/**
 *
 * @author AlexanderMS
 */
public class frameAddDependents extends javax.swing.JFrame {
    databaseDependents db = new databaseDependents();
    /**
     * Creates new form frameAddData
     */
    public frameAddDependents() {
        initComponents();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_dependent_id = new javax.swing.JLabel();
        jLabel_last_name = new javax.swing.JLabel();
        jLabel_relationship = new javax.swing.JLabel();
        jTextField_dependent_id = new javax.swing.JTextField();
        jTextField_last_name = new javax.swing.JTextField();
        jTextField_relationship = new javax.swing.JTextField();
        jButton_save = new javax.swing.JButton();
        jButton_abort = new javax.swing.JButton();
        jLabel_employee_id = new javax.swing.JLabel();
        jTextField_employee_id = new javax.swing.JTextField();
        jLabel_first_name = new javax.swing.JLabel();
        jTextField_first_name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 61, 95));

        jLabel_dependent_id.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_dependent_id.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_dependent_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_dependent_id.setText("dependent_id");

        jLabel_last_name.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_last_name.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_last_name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_last_name.setText("last_name");

        jLabel_relationship.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_relationship.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_relationship.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_relationship.setText("relationship");

        jTextField_dependent_id.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTextField_last_name.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTextField_relationship.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jButton_save.setBackground(new java.awt.Color(18, 61, 95));
        jButton_save.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_save.setForeground(new java.awt.Color(255, 255, 255));
        jButton_save.setText("Simpan");
        jButton_save.setToolTipText("");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });

        jButton_abort.setBackground(new java.awt.Color(18, 61, 95));
        jButton_abort.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_abort.setForeground(new java.awt.Color(255, 255, 255));
        jButton_abort.setText("Batal");
        jButton_abort.setToolTipText("");
        jButton_abort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_abortActionPerformed(evt);
            }
        });

        jLabel_employee_id.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_employee_id.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_employee_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_employee_id.setText("employee_id:");

        jTextField_employee_id.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel_first_name.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_first_name.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_first_name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_first_name.setText("first_name");

        jTextField_first_name.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_dependent_id)
                    .addComponent(jLabel_last_name)
                    .addComponent(jLabel_relationship)
                    .addComponent(jLabel_employee_id)
                    .addComponent(jLabel_first_name))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_relationship, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_last_name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_dependent_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jTextField_employee_id, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_first_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_save, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton_abort, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_dependent_id)
                    .addComponent(jTextField_dependent_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_first_name))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_last_name)
                    .addComponent(jTextField_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_relationship)
                    .addComponent(jTextField_relationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_employee_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_employee_id))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_save)
                    .addComponent(jButton_abort))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        db.add_data_dependents(new modelDependents(
                Integer.valueOf(jTextField_dependent_id.getText()),
                jTextField_first_name.getText(),
                jTextField_last_name.getText(),
                jTextField_relationship.getText(),
                Integer.valueOf(jTextField_employee_id.getText())
        ));
        
        JOptionPane.showMessageDialog(null, "Data Berhasil Ditambah");
        setVisible(false);

    }//GEN-LAST:event_jButton_saveActionPerformed

    private void jButton_abortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_abortActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton_abortActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_abort;
    public javax.swing.JButton jButton_save;
    private javax.swing.JLabel jLabel_dependent_id;
    private javax.swing.JLabel jLabel_employee_id;
    private javax.swing.JLabel jLabel_first_name;
    private javax.swing.JLabel jLabel_last_name;
    private javax.swing.JLabel jLabel_relationship;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextField_dependent_id;
    public javax.swing.JTextField jTextField_employee_id;
    public javax.swing.JTextField jTextField_first_name;
    public javax.swing.JTextField jTextField_last_name;
    public javax.swing.JTextField jTextField_relationship;
    // End of variables declaration//GEN-END:variables
}
