/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.frames;

import io.databases.databaseLocations;
import io.models.modelLocations;
import javax.swing.JOptionPane;

/**
 *
 * @author YRRNLMR
 */
public class frameUpdateLocations extends javax.swing.JFrame {
    databaseLocations db = new databaseLocations();
    
    /**
     * Creates new form frameUpdateLocations
     */
    public frameUpdateLocations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_location_id = new javax.swing.JLabel();
        jLabel_postal_code = new javax.swing.JLabel();
        jLabel_city = new javax.swing.JLabel();
        jTextField_location_id = new javax.swing.JTextField();
        jTextField_postal_code = new javax.swing.JTextField();
        jTextField_city = new javax.swing.JTextField();
        jButton_save = new javax.swing.JButton();
        jButton_abort = new javax.swing.JButton();
        jLabel_state_province = new javax.swing.JLabel();
        jTextField_state_province = new javax.swing.JTextField();
        jLabel_street_address = new javax.swing.JLabel();
        jTextField_street_address = new javax.swing.JTextField();
        jLabel_country_id = new javax.swing.JLabel();
        jTextField_country_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 61, 95));

        jLabel_location_id.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_location_id.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_location_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_location_id.setText("location_id");

        jLabel_postal_code.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_postal_code.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_postal_code.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_postal_code.setText("postal code");

        jLabel_city.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_city.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_city.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_city.setText("city");

        jTextField_location_id.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTextField_postal_code.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTextField_city.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jButton_save.setBackground(new java.awt.Color(18, 61, 95));
        jButton_save.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_save.setForeground(new java.awt.Color(255, 255, 255));
        jButton_save.setText("Simpan");
        jButton_save.setToolTipText("");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });

        jButton_abort.setBackground(new java.awt.Color(18, 61, 95));
        jButton_abort.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_abort.setForeground(new java.awt.Color(255, 255, 255));
        jButton_abort.setText("Batal");
        jButton_abort.setToolTipText("");
        jButton_abort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_abortActionPerformed(evt);
            }
        });

        jLabel_state_province.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_state_province.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_state_province.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_state_province.setText("state_province");

        jTextField_state_province.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel_street_address.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_street_address.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_street_address.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_street_address.setText("street address");

        jTextField_street_address.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel_country_id.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_country_id.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_country_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_country_id.setText("country_id");

        jTextField_country_id.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_location_id)
                    .addComponent(jLabel_postal_code)
                    .addComponent(jLabel_city)
                    .addComponent(jLabel_state_province)
                    .addComponent(jLabel_street_address)
                    .addComponent(jLabel_country_id))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_city, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_postal_code, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_location_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jTextField_state_province, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_street_address, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jTextField_country_id, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButton_save, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton_abort, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_location_id)
                    .addComponent(jTextField_location_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_street_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_street_address))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_postal_code)
                    .addComponent(jTextField_postal_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_city)
                    .addComponent(jTextField_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_state_province, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_state_province))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_country_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_country_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_save)
                    .addComponent(jButton_abort))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        db.update_row_locations(new modelLocations(
            Integer.valueOf(jTextField_location_id.getText()),
            jTextField_street_address.getText(),
            jTextField_postal_code.getText(),
            jTextField_city.getText(),
            jTextField_state_province.getText(),
            jTextField_country_id.getText()
        ));

        JOptionPane.showMessageDialog(null, "Data Berhasil Ditambah");
        setVisible(false);
    }//GEN-LAST:event_jButton_saveActionPerformed

    private void jButton_abortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_abortActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton_abortActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_abort;
    public javax.swing.JButton jButton_save;
    private javax.swing.JLabel jLabel_city;
    private javax.swing.JLabel jLabel_country_id;
    private javax.swing.JLabel jLabel_location_id;
    private javax.swing.JLabel jLabel_postal_code;
    private javax.swing.JLabel jLabel_state_province;
    private javax.swing.JLabel jLabel_street_address;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextField_city;
    public javax.swing.JTextField jTextField_country_id;
    public javax.swing.JTextField jTextField_location_id;
    public javax.swing.JTextField jTextField_postal_code;
    public javax.swing.JTextField jTextField_state_province;
    public javax.swing.JTextField jTextField_street_address;
    // End of variables declaration//GEN-END:variables
}
